name: Full Test Verification

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.26.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - uses: actions/checkout@v4

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: CMake
        run: |
          cmake \
          -G Ninja \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -B ${{github.workspace}}/build .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --parallel --target filter_lib_unit_integration_test filter_lib_unit_test

      - name: Run unit tests
        run: ./filter_lib_unit_test
        working-directory: ${{github.workspace}}/build/test/unit_test

      - name: Run unit integration tests
        run: ./filter_lib_unit_integration_test
        working-directory: ${{github.workspace}}/build/test/unit_integration_test

  Windows:
    runs-on: windows-2019
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.26.x'

      - uses: actions/checkout@v4

      - name: CMake
        run: cmake -B ${{github.workspace}}/build .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --parallel --target filter_lib_unit_integration_test

  Mac:
    runs-on: macos-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.26.x'

      - name: Install dependencies
        run: |
          brew install cmake ninja

      - uses: actions/checkout@v4

      - name: CMake
        run: cmake -B ${{github.workspace}}/build .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --parallel --target filter_lib_unit_integration_test
